name: template

services:
  web-devcontainer:
    build:
      context: ../.
      dockerfile: .docker/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ../.:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: development
    working_dir: /app
    #restart: always
    init: true
    command: /bin/sh -c "while sleep 1000; do :; done"
